import { useState } from "react";
import { Button } from "./ui/button";
import { Badge } from "./ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "./ui/card";
import { ScrollArea } from "./ui/scroll-area";
import { Separator } from "./ui/separator";
import { Download, FileText, Hash, HardDrive, Eye, Zap, Shield, Network, Cpu, Database, AlertTriangle, Clock, User, Globe } from "lucide-react";
import { AnalysisReport } from "./PreviousAnalysis";

interface IndividualReportProps {
  report: AnalysisReport;
  onClose?: () => void;
}

// AI-generated report sections with placeholders for future implementation
const generateAISections = (report: AnalysisReport) => ({
  executiveSummary: {
    title: "EXECUTIVE SUMMARY",
    icon: <Shield className="w-4 h-4" />,
    content: `This analysis report provides a comprehensive examination of the submitted file "${report.caseName}". The file was analyzed using advanced static and dynamic analysis techniques to identify potential threats, behavioral patterns, and security implications. Analysis completed on ${report.date} with ${report.detections} detections identified.`,
    status: "AI Analysis Pending"
  },
  
  threatAssessment: {
    title: "THREAT ASSESSMENT",
    icon: <AlertTriangle className="w-4 h-4" />,
    content: `Threat Level: ${report.threatLevel}\n\nRisk Evaluation:\n- File Size: ${report.size}\n- Hash: ${report.fileHash}\n- Analysis Status: ${report.status}\n\nThis section will contain detailed threat scoring, risk categorization, and impact assessment generated by AI analysis engines.`,
    status: "AI Analysis Pending"
  },
  
  staticAnalysis: {
    title: "STATIC ANALYSIS",
    icon: <FileText className="w-4 h-4" />,
    content: `File Information:\n- Name: ${report.caseName}\n- Hash (SHA256): ${report.fileHash}\n- Size: ${report.size}\n- Analysis Date: ${report.date}\n\nStatic analysis results will include:\n- File type identification\n- Signature analysis\n- String extraction\n- Import/Export analysis\n- Code structure examination`,
    status: "AI Analysis Pending"
  },
  
  dynamicAnalysis: {
    title: "DYNAMIC ANALYSIS",
    icon: <Cpu className="w-4 h-4" />,
    content: `Behavioral Analysis Results:\n\nRuntime behaviors will be analyzed including:\n- Process creation and termination\n- File system modifications\n- Registry changes\n- Network communications\n- Memory operations\n- API calls and system interactions\n\nExecution environment monitoring and sandbox analysis results will be displayed here.`,
    status: "AI Analysis Pending"
  },
  
  networkAnalysis: {
    title: "NETWORK ANALYSIS",
    icon: <Network className="w-4 h-4" />,
    content: `Network Communication Analysis:\n\nThis section will contain:\n- DNS queries and resolutions\n- HTTP/HTTPS requests\n- TCP/UDP connections\n- Suspicious IP addresses\n- Command and Control communications\n- Data exfiltration attempts\n- Network protocol analysis`,
    status: "AI Analysis Pending"
  },
  
  behaviorAnalysis: {
    title: "BEHAVIOR ANALYSIS",
    icon: <Zap className="w-4 h-4" />,
    content: `Malicious Behavior Patterns:\n\nIdentified behaviors will include:\n- Persistence mechanisms\n- Privilege escalation attempts\n- Anti-analysis techniques\n- Evasion methods\n- Payload deployment\n- System compromise indicators\n- Lateral movement patterns`,
    status: "AI Analysis Pending"
  },
  
  indicatorsOfCompromise: {
    title: "INDICATORS OF COMPROMISE",
    icon: <Database className="w-4 h-4" />,
    content: `IOC Summary:\n\nThis section will list:\n- File hashes (MD5, SHA1, SHA256)\n- IP addresses and domains\n- Registry keys and values\n- File paths and names\n- Mutex names\n- Process names\n- Network signatures\n- YARA rules`,
    status: "AI Analysis Pending"
  },
  
  mitigationRecommendations: {
    title: "MITIGATION RECOMMENDATIONS",
    icon: <Shield className="w-4 h-4" />,
    content: `Security Recommendations:\n\nBased on analysis results, recommendations will include:\n- Immediate containment actions\n- System hardening measures\n- Network segmentation advice\n- Monitoring and detection rules\n- Incident response procedures\n- Prevention strategies\n- Recovery procedures`,
    status: "AI Analysis Pending"
  },
  
  technicalDetails: {
    title: "TECHNICAL DETAILS",
    icon: <HardDrive className="w-4 h-4" />,
    content: `Technical Analysis Results:\n\nDetailed technical information will include:\n- Assembly code analysis\n- Function call graphs\n- Control flow analysis\n- Data flow analysis\n- Cryptographic analysis\n- Packing and obfuscation detection\n- Debugging information`,
    status: "AI Analysis Pending"
  },
  
  timelineAnalysis: {
    title: "TIMELINE ANALYSIS",
    icon: <Clock className="w-4 h-4" />,
    content: `Event Timeline:\n\nChronological analysis of events:\n- File creation and modification times\n- Process execution timeline\n- Network activity timeline\n- System changes timeline\n- Attack progression\n- Persistence establishment\n- Data access patterns`,
    status: "AI Analysis Pending"
  }
});

export const IndividualReport = ({ report, onClose }: IndividualReportProps) => {
  const [selectedSection, setSelectedSection] = useState<string | null>(null);
  const aiSections = generateAISections(report);

  const handleDownloadPDF = () => {
    console.log("Downloading PDF report for:", report.caseName);
    // Future implementation: Generate and download PDF
  };

  const sectionKeys = Object.keys(aiSections) as Array<keyof typeof aiSections>;

  return (
    <div className="h-full bg-gradient-subtle flex">
      {/* Sidebar Navigation */}
      <div className="w-80 bg-background-secondary/50 border-r border-border flex flex-col">
        <div className="p-4 border-b border-border">
          <div className="flex items-center justify-between mb-2">
            <h2 className="text-lg font-semibold text-foreground">Report Sections</h2>
            {onClose && (
              <Button variant="ghost" size="sm" onClick={onClose}>
                ×
              </Button>
            )}
          </div>
          <div className="text-sm text-muted-foreground">
            <p className="font-medium">{report.caseName}</p>
            <p className="text-xs">Analysis ID: {report.id}</p>
          </div>
        </div>
        
        <ScrollArea className="flex-1">
          <div className="p-2 space-y-1">
            {sectionKeys.map((key) => {
              const section = aiSections[key];
              return (
                <Button
                  key={key}
                  variant={selectedSection === key ? "secondary" : "ghost"}
                  className="w-full justify-start h-auto p-3 text-left"
                  onClick={() => setSelectedSection(key)}
                >
                  <div className="flex items-center gap-2">
                    {section.icon}
                    <div>
                      <div className="text-sm font-medium">{section.title}</div>
                      <div className="text-xs text-muted-foreground">{section.status}</div>
                    </div>
                  </div>
                </Button>
              );
            })}
          </div>
        </ScrollArea>
        
        <div className="p-4 border-t border-border">
          <Button 
            onClick={handleDownloadPDF} 
            className="w-full bg-primary hover:bg-primary/90 text-primary-foreground"
          >
            <Download className="w-4 h-4 mr-2" />
            Download PDF Report
          </Button>
        </div>
      </div>

      {/* Main Content */}
      <div className="flex-1 flex flex-col">
        {/* Header */}
        <div className="p-6 border-b border-border bg-background-secondary/30">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-2xl font-bold text-foreground">Malware Analysis Report</h1>
              <p className="text-sm text-muted-foreground">
                Generated on {report.date} | Case: {report.caseName}
              </p>
            </div>
            <div className="flex items-center gap-2">
              <Badge variant={report.threatLevel === 'Critical' ? 'destructive' : 
                           report.threatLevel === 'High' ? 'destructive' :
                           report.threatLevel === 'Medium' ? 'secondary' : 'outline'}>
                {report.threatLevel} Risk
              </Badge>
              <Badge variant={report.status === 'Completed' ? 'default' : 
                           report.status === 'Processing' ? 'secondary' : 'destructive'}>
                {report.status}
              </Badge>
            </div>
          </div>
        </div>

        {/* Content Area */}
        <ScrollArea className="flex-1">
          <div className="max-w-4xl mx-auto p-6">
            {selectedSection ? (
              <Card className="bg-background-tertiary border-border">
                <CardHeader>
                  <CardTitle className="text-lg font-semibold text-foreground uppercase tracking-wide flex items-center">
                    {aiSections[selectedSection as keyof typeof aiSections].icon}
                    <span className="ml-2">{aiSections[selectedSection as keyof typeof aiSections].title}</span>
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-4">
                    <div className="bg-background-secondary/50 rounded-lg p-4 border border-border">
                      <pre className="text-foreground whitespace-pre-wrap text-sm leading-relaxed">
                        {aiSections[selectedSection as keyof typeof aiSections].content}
                      </pre>
                    </div>
                    
                    <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
                      <div className="flex items-center gap-2 text-yellow-800">
                        <AlertTriangle className="w-4 h-4" />
                        <span className="font-medium">AI Analysis Status</span>
                      </div>
                      <p className="text-yellow-700 text-sm mt-1">
                        This section contains placeholder content. AI analysis will be implemented in future updates to provide detailed, automated analysis results.
                      </p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ) : (
              <div className="text-center py-12">
                <FileText className="w-16 h-16 text-muted-foreground mx-auto mb-4" />
                <h3 className="text-lg font-semibold text-foreground mb-2">Select a Report Section</h3>
                <p className="text-muted-foreground">
                  Choose a section from the sidebar to view detailed analysis results.
                </p>
              </div>
            )}
          </div>
        </ScrollArea>
      </div>
    </div>
  );
};
